---
title: "Katz Back-Off Test"
author: "Sukhovei Mikhail"
date: "22 09 2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

source("TypeAssistant/algorithm.R")
source("TypeAssistant/utils.R")
```

```{r cars}
load(file = "TypeAssistant/unigrams.Rdata")
load(file = "TypeAssistant/bigrams.Rdata")
load(file = "TypeAssistant/trigrams.Rdata")
load(file = "TypeAssistant/tetragrams.Rdata")
load(file = "TypeAssistant/pentagrams.Rdata")

test <- read.csv("test/test.csv")

ind <- 1:nrow(test)

pred_top1 <- list()
pred_top3 <- list()
for (i in ind) {
    tokens <- clean_and_tokenize(test$text[i])
    pred <- KBO_predict(
        tokens[[1]],
        list(unigrams, bigrams, trigrams, tetragrams, pentagrams),
        pred_num = 3
    )
    pred_top1[[i]] <- pred$pred[1]
    pred_top3[[i]] <- pred$pred[1:3]
}
```

```{r}
cor_top1 <- sapply(ind, function(i) {test$next_word[i] == pred_top1[[i]]})
cor_top3 <- sapply(ind, function(i) {any(test$next_word[i] == pred_top3[[i]])})

print(sprintf(
    "Top-1 accuracy: %.0f%%",
    100 * (sum(cor_top1) / length(cor_top1))
))
print(sprintf(
    "Top-3 accuracy: %.0f%%",
    100 * (sum(cor_top3) / length(cor_top3))
))
```
